export interface TradingPlatform {
  id: string;
  name: string;
  logo: string;
  description: string;
  minDeposit: string;
  commissionPerTrade: string;
  accountTypes: string[];
  features: {
    mobileApp: boolean;
    advancedCharting: boolean;
    paperTrading: boolean;
    fractionalShares: boolean;
    optionsTrading: boolean;
    marginTrading: boolean;
    researchTools: boolean;
    educationalResources: boolean;
  };
  founded: number;
  accounts: number;
  rating: number;
  trustScore: number;
  website: string;
}

export const tradingPlatforms: TradingPlatform[] = [
  {
    id: "fidelity",
    name: "Fidelity Investments",
    logo: "🏛️",
    description: "One of the largest investment firms in the US with comprehensive trading tools and research",
    minDeposit: "None",
    commissionPerTrade: "$0",
    accountTypes: ["Individual", "Joint", "IRA", "401(k)"],
    features: {
      mobileApp: true,
      advancedCharting: true,
      paperTrading: true,
      fractionalShares: true,
      optionsTrading: true,
      marginTrading: true,
      researchTools: true,
      educationalResources: true,
    },
    founded: 1946,
    accounts: 12000000,
    rating: 4.8,
    trustScore: 98,
    website: "https://www.fidelity.com",
  },
  {
    id: "charles-schwab",
    name: "Charles Schwab",
    logo: "📊",
    description: "Industry pioneer offering zero-commission trading and excellent customer service",
    minDeposit: "None",
    commissionPerTrade: "$0",
    accountTypes: ["Individual", "Joint", "IRA", "Trust"],
    features: {
      mobileApp: true,
      advancedCharting: true,
      paperTrading: true,
      fractionalShares: true,
      optionsTrading: true,
      marginTrading: true,
      researchTools: true,
      educationalResources: true,
    },
    founded: 1971,
    accounts: 16000000,
    rating: 4.7,
    trustScore: 97,
    website: "https://www.schwab.com",
  },
  {
    id: "etrade",
    name: "E*TRADE",
    logo: "⚡",
    description: "Innovative platform with powerful tools for active traders and beginner-friendly features",
    minDeposit: "None",
    commissionPerTrade: "$0",
    accountTypes: ["Individual", "Joint", "IRA", "Custodial"],
    features: {
      mobileApp: true,
      advancedCharting: true,
      paperTrading: true,
      fractionalShares: true,
      optionsTrading: true,
      marginTrading: true,
      researchTools: true,
      educationalResources: true,
    },
    founded: 1982,
    accounts: 5000000,
    rating: 4.6,
    trustScore: 96,
    website: "https://us.etrade.com",
  },
  {
    id: "td-ameritrade",
    name: "TD Ameritrade",
    logo: "🎯",
    description: "Comprehensive platform with thinkorswim trading software and extensive educational resources",
    minDeposit: "None",
    commissionPerTrade: "$0",
    accountTypes: ["Individual", "Joint", "IRA", "Trust"],
    features: {
      mobileApp: true,
      advancedCharting: true,
      paperTrading: true,
      fractionalShares: true,
      optionsTrading: true,
      marginTrading: true,
      researchTools: true,
      educationalResources: true,
    },
    founded: 1975,
    accounts: 7000000,
    rating: 4.7,
    trustScore: 96,
    website: "https://www.tdameritrade.com",
  },
  {
    id: "interactive-brokers",
    name: "Interactive Brokers",
    logo: "🌐",
    description: "Professional-grade platform ideal for active traders with global market access",
    minDeposit: "$500",
    commissionPerTrade: "$1",
    accountTypes: ["Individual", "Joint", "IRA", "Corporate"],
    features: {
      mobileApp: true,
      advancedCharting: true,
      paperTrading: true,
      fractionalShares: false,
      optionsTrading: true,
      marginTrading: true,
      researchTools: true,
      educationalResources: true,
    },
    founded: 1993,
    accounts: 1000000,
    rating: 4.5,
    trustScore: 94,
    website: "https://www.interactivebrokers.com",
  },
  {
    id: "webull",
    name: "Webull",
    logo: "📱",
    description: "Modern mobile-first platform with extended trading hours and commission-free trading",
    minDeposit: "None",
    commissionPerTrade: "$0",
    accountTypes: ["Individual", "Joint"],
    features: {
      mobileApp: true,
      advancedCharting: true,
      paperTrading: true,
      fractionalShares: true,
      optionsTrading: true,
      marginTrading: true,
      researchTools: true,
      educationalResources: true,
    },
    founded: 2017,
    accounts: 3000000,
    rating: 4.4,
    trustScore: 88,
    website: "https://www.webull.com",
  },
  {
    id: "tastytrade",
    name: "tastytrade",
    logo: "🍴",
    description: "Specialized platform for options traders with educational focus and competitive pricing",
    minDeposit: "$2,000",
    commissionPerTrade: "$0",
    accountTypes: ["Individual", "Joint", "IRA"],
    features: {
      mobileApp: true,
      advancedCharting: true,
      paperTrading: true,
      fractionalShares: false,
      optionsTrading: true,
      marginTrading: true,
      researchTools: true,
      educationalResources: true,
    },
    founded: 2011,
    accounts: 500000,
    rating: 4.6,
    trustScore: 92,
    website: "https://www.tastytrade.com",
  },
  {
    id: "ally-invest",
    name: "Ally Invest",
    logo: "🤝",
    description: "Part of Ally Bank with competitive pricing and strong customer support",
    minDeposit: "None",
    commissionPerTrade: "$0",
    accountTypes: ["Individual", "Joint", "IRA"],
    features: {
      mobileApp: true,
      advancedCharting: true,
      paperTrading: true,
      fractionalShares: true,
      optionsTrading: true,
      marginTrading: true,
      researchTools: true,
      educationalResources: true,
    },
    founded: 2009,
    accounts: 1000000,
    rating: 4.3,
    trustScore: 90,
    website: "https://www.ally.com",
  },
  {
    id: "merrill-edge",
    name: "Merrill Edge",
    logo: "🏦",
    description: "Bank of America's trading platform with integrated banking and investment services",
    minDeposit: "None",
    commissionPerTrade: "$0",
    accountTypes: ["Individual", "Joint", "IRA", "Trust"],
    features: {
      mobileApp: true,
      advancedCharting: true,
      paperTrading: true,
      fractionalShares: true,
      optionsTrading: true,
      marginTrading: true,
      researchTools: true,
      educationalResources: true,
    },
    founded: 2010,
    accounts: 2000000,
    rating: 4.5,
    trustScore: 95,
    website: "https://www.merrilledge.com",
  },
  {
    id: "firstrade",
    name: "Firstrade",
    logo: "🚀",
    description: "Budget-friendly platform with zero commissions and no account minimums",
    minDeposit: "None",
    commissionPerTrade: "$0",
    accountTypes: ["Individual", "Joint", "IRA"],
    features: {
      mobileApp: true,
      advancedCharting: true,
      paperTrading: true,
      fractionalShares: true,
      optionsTrading: true,
      marginTrading: false,
      researchTools: true,
      educationalResources: true,
    },
    founded: 1985,
    accounts: 500000,
    rating: 4.2,
    trustScore: 89,
    website: "https://www.firstrade.com",
  },
];

export const featureLabels: Record<keyof TradingPlatform["features"], string> = {
  mobileApp: "Mobile App",
  advancedCharting: "Advanced Charting",
  paperTrading: "Paper Trading",
  fractionalShares: "Fractional Shares",
  optionsTrading: "Options Trading",
  marginTrading: "Margin Trading",
  researchTools: "Research Tools",
  educationalResources: "Educational Resources",
};
